// users+followers лучше хранить в Neo4j, но можно обойтись и РСУБД (MySql/Postgres).
// posts+comments+atachments храним в другой БД (MySql/Postgres)
// фотографии будем хранить в третьей бд - Azure Blob Storage (CDN?)

Table users {
  id uuid [primary key]
  username varchar
  image_url varchar
  created_at timestamp
  
  Indexes {
    id [unique]
  }
}

Table followers {
  following_user_id uuid
  followed_user_id uuid
  created_at timestamp
  Indexes {
    (followed_user_id, following_user_id) [name:"idx_followed_user_id_following_user_id", unique]
  }
}

Table posts {
  id uuid [primary key]
  user_id uuid
  description text [note: 'Content of the post']
  created_at timestamp
  }

Table comments {
  id uuid [primary key]
  post_id uuid
  user_id uuid
  image_url varchar
  comment varchar
  created_at timestamp
}

Table atachments {
  id uuid [primary key]
  post_id uuid
  image_id uuid
  image_url varchar
  created_at timestamp
}

Ref: posts.user_id > users.id // many-to-one
Ref: posts.id < atachments.post_id// many-to-one

Ref: comments.post_id > posts.id // one-to-one
Ref: comments.user_id > users.id // one-to-one

Ref: users.id < followers.following_user_id
Ref: users.id < followers.followed_user_id
