// 1БД. users+followers харним в графовой БД (Neo4j). Удобное хранение и поиск отношений.
// 2БД. posts+comments храним в РСУБД (MySql/Postgres). Посты терять нельзя, выбирал между РСУБД и документо-ориентированной БД. Посты хорошо на документ ложатся, а вот комментарии не очень.
// 3БД. chats+messages храним в РСУБД (MySql/Postgres). Могла бы быть mongoDB, где один документ - это набор сообщений между двумя пользователями. Но размер документа ограничен, долгая переписка может превысить его.
// 4БД. фотографии будем хранить в blob-storage (AzureBlobStorage/S3). Наиболее подходит для картинок.
// 5БД. Координаты будем хранить в геоБД (PostGIS). Наиболее подходит для координат, дает мощный поиск.

Table users {
  id uuid [primary key]
  username varchar
  image_url varchar
  created_at timestamp
  
  Indexes {
    id [unique]
  }
}

Table followers {
  id uuid
  following_user_id uuid
  followed_user_id uuid
  created_at timestamp
  Indexes {
    (followed_user_id, following_user_id) [name:"idx_followed_user_id_following_user_id", unique]
  }
}

Table posts {
  id uuid [primary key]
  user_id uuid
  description text [note: 'Content of the post']
  created_at timestamp
  images json [note: 'Array of image_url']
  locationId uuid
  }

Table comments {
  id uuid [primary key]
  reply_comment_id uuid
  post_id uuid
  user_id uuid
  image_url varchar
  comment varchar
  created_at timestamp
}

Table locations {
  id uuid
  latitude decimal
  longitude decimal
}

Table chats {
  id uuid
  from uuid
  to uuid
}

Table messages {
  id uuid
  chat_id uuid
  from uuid
  to uuid
  created_at timestamp
  message_text varchar
}

Ref: posts.user_id > users.id // many-to-one

Ref: comments.post_id > posts.id // many-to-one
Ref: comments.user_id - users.id // one-to-one
Ref: locations.id - posts.locationId // one-to-one

Ref: users.id < followers.following_user_id
Ref: users.id < followers.followed_user_id

Ref: messages.chat_id > chats.id
Ref: chats.from - users.id
Ref: chats.to - users.id
Ref: messages.from - users.id
Ref: messages.to - users.id
