openapi: 3.0.0

tags:
  - name: SocialNetwork
  - name: Identity

info:
  title: SocialNetwork API
  description: Current API describes interaction with SocialNetwork
  version: 1.0.0

paths:
  /tiny_urls:
    post:
      summary: Create tiny url
      description: Method creates tiny url from long url
      tags:
        - SocialNetwork
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                long_url:
                  type: string
                  description: long url
              required:
                - long_url
            examples:
              request:
                value:
                  long_url: "https://test.com/long_long_long_url"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: id of the tiny url
                  tiny_url:
                    type: string
                    description: tiny url for long url
                required:
                  - id
                  - tiny_url
              examples:
                response:
                  value:
                    id: "12ae3c"
                    tiny_url: "https://tiny_url.ru/12ae3c"
        400:
          description: Bad Request
        500:
          description: Server error

  /tiny_urls/{id}:
    delete:
      summary: Remove tiny url
      description: Method removes tiny url
      tags:
        - SocialNetwork
      parameters:
        - name: id
          in: path
          required: true
          description: Tiny url id (uri of the tiny url)
          schema:
            type : string
      responses:
        200:
          description: Ok
        404:
          description: Not found
        500:
          description: Server error

  /feed:
    get:
      summary: Redirect to long url
      description: Method 
      tags:
        - SocialNetwork
      parameters:
        - name: id
          in: path
          required: true
          description: Tiny url id (uri of the tiny url)
          schema:
            type : string
      responses:
        302:
          description: Redirect
        404:
          description: Not found
        500:
          description: Server error

  /identity/auth:
    post:
      summary: Create auth token
      description: Method creates auth token for user with phone number
      tags:
        - Identity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: phone number
              required:
                - phone
            examples:
              request:
                value:
                  phone: "+79001234567"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: authentication access_token
                  token_type:
                    type: string
                    description: type of token
                  expires_in:
                    type: number
                    description: token expiration time
                  refresh_token:
                    type: string
                    description: token for refresh
                required:
                  - access_token
                  - token_type
                  - expires_in
                  - refresh_token
              examples:
                response:
                  value:
                    access_token: "tGzv3JOkF0XG5Qx2TlKWIA"
                    token_type: "Bearer"
                    expires_in: 3600
                    refresh_token: "tGzv3JOkF0XG5Qx2TlKWIA"
        400:
          description: Bad Request
        500:
          description: Server error